Math 150 Hw8 Tommy Lee Truong

Last Edit: May 20 2021

In [45]:
import matplotlib
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
p=np.zeros((3,3))

The current Math 150 fever distribution is [60%,10%,30%]

In [46]:
v=np.matrix([.6,.1,.3])


This means 10% of the population is currently infected and 30% was previously infected therefore the S->I rate is 40% and S->S remains at 60%

In [47]:
p[0,:]=np.matrix([.6,.4,0])

Propose the distribution represented 100 people, 40 people were infected at some point and 30 of them recovered. Therefore the I->R rate is 30/40 or 75% and I-I is left with 25%

In [48]:
p[1,:]= np.matrix([0,.25,.75])

Propose that the current distribution represents a passage of time in which half the popultaion has been infected atleast once, it stans to reason that 10/60 susceptible individuals have once been in a state of recovery.This makes the true number of recovered infdividuals 40 and thus R->S must be 10/40 or 25% and R->R 75%

In [49]:
p[2,:]= np.matrix([.25,0,.75])

In [50]:
print(p)

[[0.6  0.4  0.  ]
 [0.   0.25 0.75]
 [0.25 0.   0.75]]


In [52]:
x=v
print(x)
for i in range(75):
    x=x*p
print(x)

[[0.6 0.1 0.3]]
[[0.31914894 0.17021277 0.5106383 ]]


After 75 days it seems approximatly a third of the population still remain susceptible, a sixth remain infected, and half have recovered. 